"""RAG knowledge base REST routes."""

from __future__ import annotations

import json
import logging
import os
import re
from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from typing import Any

from flask import Flask, jsonify, request

logger = logging.getLogger(__name__)


def register_rag_routes(
    app: Flask,
    db_path: str,
    require_permissions,
    *,
    start_background_task: Callable[..., str] | None = None,
    get_kb_tasks: Callable[[str, int], dict[str, list[dict[str, Any]]]] | None = None,
) -> None:
    from ai_actuarial.storage import Storage

    try:
        from ai_actuarial.rag.knowledge_base import KnowledgeBaseManager
    except ImportError:
        rag_available = False
    else:
        rag_available = True

    def _api_error(message: str, *, status_code: int, detail: str | None = None):
        payload: dict[str, Any] = {"success": False, "error": message}
        if detail and os.getenv("EXPOSE_ERROR_DETAILS"):
            payload["detail"] = detail
        return jsonify(payload), status_code

    def _api_success(data: Any = None, message: str | None = None, status_code: int = 200):
        payload: dict[str, Any] = {"success": True}
        if data is not None:
            payload["data"] = data
        if message:
            payload["message"] = message
        return jsonify(payload), status_code

    def _check_rag_available():
        if not rag_available:
            return _api_error("RAG functionality not available", status_code=503)
        return None

    def _check_config_write_auth():
        expected_token = app.config.get("CONFIG_WRITE_AUTH_TOKEN") or os.getenv(
            "CONFIG_WRITE_AUTH_TOKEN"
        )
        if expected_token:
            provided_token = request.headers.get("X-Auth-Token")
            if not provided_token or provided_token != expected_token:
                logger.warning("RAG write operation rejected: authentication failed")
                return _api_error("Forbidden", status_code=403)
        return None

    def _norm(s: Any) -> str:
        return str(s or "").strip()

    def _list(v: Any, field: str) -> list[str]:
        if v is None:
            return []
        if not isinstance(v, list):
            raise ValueError(f"{field} must be a list")
        out: list[str] = []
        for item in v:
            val = _norm(item)
            if val and val not in out:
                out.append(val)
        return out

    def _kb_id(kb_id: Any) -> str:
        val = _norm(kb_id)
        if not val:
            raise ValueError("kb_id is required")
        # Keep a reasonable length constraint, but do not restrict the character set
        # so that KB IDs generated by KnowledgeBaseManager (e.g. from categories)
        # remain accessible via this API.
        if not (2 <= len(val) <= 64):
            raise ValueError("kb_id must be between 2 and 64 characters long")
        return val

    def _serialize_kb(kb) -> dict[str, Any]:
        return {
            "kb_id": kb.kb_id,
            "name": kb.name,
            "description": kb.description,
            "kb_mode": kb.kb_mode,
            "embedding_model": kb.embedding_model,
            "chunk_size": kb.chunk_size,
            "chunk_overlap": kb.chunk_overlap,
            "index_type": kb.index_type,
            "file_count": kb.file_count,
            "chunk_count": kb.chunk_count,
            "created_at": kb.created_at,
            "updated_at": kb.updated_at,
        }

    def _build_category_where(categories: list[str]) -> tuple[str, list[str]]:
        if not categories:
            return "1=0", []
        parts: list[str] = []
        params: list[str] = []
        for category in categories:
            parts.append("(c.category = ? OR c.category LIKE ? OR c.category LIKE ? OR c.category LIKE ?)")
            params.extend([category, f"{category};%", f"%; {category}", f"%; {category};%"])
        return " OR ".join(parts), params

    def _with_manager(fn):
        storage = Storage(db_path)
        try:
            return fn(KnowledgeBaseManager(storage), storage)
        finally:
            storage.close()

    @app.route("/api/rag/knowledge-bases", methods=["GET"])
    @require_permissions("catalog.read")
    def api_rag_list_kbs():
        if (r := _check_rag_available()) is not None:
            return r
        try:
            kb_mode = _norm(request.args.get("kb_mode"))
            search = _norm(request.args.get("search")).lower()

            def _run(kb_manager, _storage):
                kbs = kb_manager.list_kbs()
                if kb_mode:
                    kbs = [kb for kb in kbs if kb.kb_mode == kb_mode]
                if search:
                    kbs = [
                        kb
                        for kb in kbs
                        if search in (kb.name or "").lower()
                        or search in (kb.description or "").lower()
                        or search in (kb.kb_id or "").lower()
                    ]
                return _api_success([_serialize_kb(kb) for kb in kbs])

            return _with_manager(_run)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error listing KBs")
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases", methods=["POST"])
    @require_permissions("config.write")
    def api_rag_create_kb():
        if (r := _check_rag_available()) is not None:
            return r
        if (r := _check_config_write_auth()) is not None:
            return r
        try:
            data = request.get_json(silent=True)
            if not isinstance(data, dict):
                return _api_error("Invalid JSON body", status_code=400)
            kb_id = _kb_id(data.get("kb_id"))
            name = _norm(data.get("name"))
            if not name:
                return _api_error("name is required", status_code=400)
            kb_mode = _norm(data.get("kb_mode") or "manual").lower()
            if kb_mode not in {"manual", "category"}:
                return _api_error("kb_mode must be 'category' or 'manual'", status_code=400)
            chunk_size = int(data.get("chunk_size") or 800)
            chunk_overlap = int(data.get("chunk_overlap") or 100)
            categories = _list(data.get("categories"), "categories")
            file_urls = _list(data.get("file_urls"), "file_urls")
            if kb_mode == "category" and not categories:
                return _api_error("categories required for category mode", status_code=400)

            def _run(kb_manager, _storage):
                if kb_manager.get_kb(kb_id):
                    return _api_error(f"Knowledge base '{kb_id}' already exists", status_code=409)
                kb_manager.create_kb(
                    kb_id=kb_id,
                    name=name,
                    description=_norm(data.get("description")),
                    kb_mode=kb_mode,
                    embedding_model=_norm(data.get("embedding_model") or "text-embedding-3-large"),
                    chunk_size=chunk_size,
                    chunk_overlap=chunk_overlap,
                )
                if kb_mode == "category":
                    kb_manager.link_kb_to_categories(kb_id, categories)
                elif file_urls:
                    kb_manager.add_files_to_kb(kb_id, file_urls)
                kb = kb_manager.get_kb(kb_id)
                return _api_success(
                    _serialize_kb(kb),
                    message=f"Knowledge base '{name}' created successfully",
                    status_code=201,
                )

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error creating KB")
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>", methods=["GET"])
    @require_permissions("catalog.read")
    def api_rag_get_kb(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)

            def _run(kb_manager, _storage):
                kb = kb_manager.get_kb(kid)
                if not kb:
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                payload = _serialize_kb(kb)
                payload["stats"] = kb_manager.get_kb_stats(kid)
                payload["categories"] = kb_manager.get_kb_categories(kid)
                return _api_success(payload)

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error getting KB %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>", methods=["PUT"])
    @require_permissions("config.write")
    def api_rag_update_kb(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        if (r := _check_config_write_auth()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)
            data = request.get_json(silent=True)
            if not isinstance(data, dict):
                return _api_error("Invalid JSON body", status_code=400)
            name = _norm(data["name"]) if "name" in data else None
            description = _norm(data["description"]) if "description" in data else None
            if name is None and description is None:
                return _api_error("No valid update fields provided (name, description)", status_code=400)

            def _run(kb_manager, _storage):
                if not kb_manager.get_kb(kid):
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                kb_manager.update_kb(kid, name=name, description=description)
                return _api_success(_serialize_kb(kb_manager.get_kb(kid)))

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error updating KB %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>", methods=["DELETE"])
    @require_permissions("config.write")
    def api_rag_delete_kb(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        if (r := _check_config_write_auth()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)

            def _run(kb_manager, _storage):
                if not kb_manager.get_kb(kid):
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                kb_manager.delete_kb(kid)
                return _api_success(message=f"Knowledge base '{kid}' deleted successfully")

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error deleting KB %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>/files", methods=["GET"])
    @require_permissions("catalog.read")
    def api_rag_list_kb_files(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)
            status_filter = _norm(request.args.get("status")).lower()

            def _run(kb_manager, _storage):
                if not kb_manager.get_kb(kid):
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                rows = []
                for item in kb_manager.get_kb_files(kid):
                    indexed = item.get("indexed_at") is not None
                    stale = bool(item.get("needs_reindex"))
                    status = "indexed" if indexed and not stale else ("stale" if indexed else "pending")
                    rows.append(
                        {
                            "file_url": item.get("file_url"),
                            "title": item.get("title") or "",
                            "category": item.get("category") or "",
                            "source_site": item.get("source_site") or "",
                            "added_at": item.get("added_at"),
                            "indexed_at": item.get("indexed_at"),
                            "markdown_updated_at": item.get("markdown_updated_at"),
                            "chunk_count": item.get("chunk_count") or 0,
                            "indexed": indexed,
                            "needs_reindex": stale,
                            "status": status,
                        }
                    )
                if status_filter:
                    rows = [row for row in rows if row.get("status") == status_filter]
                return _api_success({"kb_id": kid, "total_files": len(rows), "files": rows})

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error listing KB files %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>/files", methods=["POST"])
    @require_permissions("config.write")
    def api_rag_add_kb_files(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        if (r := _check_config_write_auth()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)
            data = request.get_json(silent=True)
            if not isinstance(data, dict):
                return _api_error("Invalid JSON body", status_code=400)
            file_urls = _list(data.get("file_urls"), "file_urls")
            if not file_urls:
                return _api_error("file_urls must be a non-empty list", status_code=400)

            def _run(kb_manager, _storage):
                if not kb_manager.get_kb(kid):
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                result = kb_manager.add_files_to_kb(kid, file_urls)
                return _api_success(
                    {
                        "kb_id": kid,
                        "added_count": result.get("added_count", 0),
                        "skipped_count": result.get("skipped_count", 0),
                        "total_files": result.get("total_files", 0),
                    }
                )

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error adding files to KB %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>/files/<path:file_url>", methods=["DELETE"])
    @require_permissions("config.write")
    def api_rag_remove_kb_file(kb_id: str, file_url: str):
        if (r := _check_rag_available()) is not None:
            return r
        if (r := _check_config_write_auth()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)

            def _run(kb_manager, _storage):
                if not kb_manager.get_kb(kid):
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                removed = kb_manager.remove_files_from_kb(kid, [file_url])
                if removed <= 0:
                    return _api_error("File not found in knowledge base", status_code=404)
                return _api_success(message=f"File removed from KB '{kid}'")

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error removing KB file %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/categories/unmapped", methods=["GET"])
    @require_permissions("catalog.read")
    def api_rag_unmapped_categories():
        if (r := _check_rag_available()) is not None:
            return r
        try:
            def _run(kb_manager, _storage):
                rows = kb_manager.get_unmapped_categories()
                return _api_success(
                    {
                        "unmapped_categories": [
                            {"name": row.get("category"), "file_count": row.get("file_count") or 0}
                            for row in rows
                        ],
                        "total_count": len(rows),
                    }
                )

            return _with_manager(_run)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error listing unmapped categories")
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/categories/stats", methods=["POST"])
    @require_permissions("catalog.read")
    def api_rag_category_stats():
        if (r := _check_rag_available()) is not None:
            return r
        try:
            data = request.get_json(silent=True)
            if not isinstance(data, dict):
                return _api_error("Invalid JSON body", status_code=400)
            categories = _list(data.get("categories"), "categories")
            kb_id_raw = _norm(data.get("kb_id"))
            kb_id = _kb_id(kb_id_raw) if kb_id_raw else ""
            where_sql, params = _build_category_where(categories)

            def _run(kb_manager, storage):
                if kb_id and not kb_manager.get_kb(kb_id):
                    return _api_error(f"Knowledge base '{kb_id}' not found", status_code=404)
                if not categories:
                    return _api_success(
                        {
                            "categories": [],
                            "unique_files": 0,
                            "unique_markdown_files": 0,
                            "in_kb_files": 0,
                            "in_kb_markdown_files": 0,
                        }
                    )

                sql = f"""
                    WITH matched AS (
                        SELECT DISTINCT
                            c.file_url AS file_url,
                            CASE
                                WHEN c.markdown_content IS NOT NULL AND c.markdown_content != '' THEN 1
                                ELSE 0
                            END AS has_markdown
                        FROM catalog_items c
                        JOIN files f ON f.url = c.file_url
                        WHERE f.deleted_at IS NULL
                          AND ({where_sql})
                    )
                    SELECT
                        COUNT(*) AS unique_files,
                        COALESCE(SUM(has_markdown), 0) AS unique_markdown_files,
                        COALESCE(SUM(CASE WHEN kf.file_url IS NOT NULL THEN 1 ELSE 0 END), 0) AS in_kb_files,
                        COALESCE(
                            SUM(CASE WHEN kf.file_url IS NOT NULL AND has_markdown = 1 THEN 1 ELSE 0 END),
                            0
                        ) AS in_kb_markdown_files
                    FROM matched m
                    LEFT JOIN rag_kb_files kf
                      ON kf.file_url = m.file_url
                     AND (? = '' OR kf.kb_id = ?)
                """
                row = storage._conn.execute(sql, params + [kb_id, kb_id]).fetchone()
                return _api_success(
                    {
                        "categories": categories,
                        "unique_files": int(row[0] or 0),
                        "unique_markdown_files": int(row[1] or 0),
                        "in_kb_files": int(row[2] or 0),
                        "in_kb_markdown_files": int(row[3] or 0),
                    }
                )

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error getting category stats")
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/files/selectable", methods=["GET"])
    @require_permissions("catalog.read")
    def api_rag_selectable_files():
        if (r := _check_rag_available()) is not None:
            return r
        try:
            query = _norm(request.args.get("query")).lower()
            category = _norm(request.args.get("category"))
            kb_id_raw = _norm(request.args.get("kb_id"))
            kb_id = _kb_id(kb_id_raw) if kb_id_raw else ""
            limit = max(1, min(int(_norm(request.args.get("limit")) or "100"), 500))
            offset = max(0, int(_norm(request.args.get("offset")) or "0"))

            where_parts = [
                "f.deleted_at IS NULL",
                "c.markdown_content IS NOT NULL",
                "c.markdown_content != ''",
            ]
            params: list[Any] = []

            if query:
                where_parts.append(
                    "(LOWER(f.title) LIKE ? OR LOWER(f.original_filename) LIKE ? OR LOWER(f.url) LIKE ?)"
                )
                q = f"%{query}%"
                params.extend([q, q, q])

            if category:
                where_parts.append(
                    "(c.category = ? OR c.category LIKE ? OR c.category LIKE ? OR c.category LIKE ?)"
                )
                params.extend([category, f"{category};%", f"%; {category}", f"%; {category};%"])

            if kb_id:
                where_parts.append(
                    "NOT EXISTS (SELECT 1 FROM rag_kb_files kf WHERE kf.kb_id = ? AND kf.file_url = f.url)"
                )
                params.append(kb_id)

            where_sql = " AND ".join(where_parts)

            def _run(kb_manager, storage):
                if kb_id and not kb_manager.get_kb(kb_id):
                    return _api_error(f"Knowledge base '{kb_id}' not found", status_code=404)

                count_sql = f"""
                    SELECT COUNT(*)
                    FROM files f
                    JOIN catalog_items c ON c.file_url = f.url
                    WHERE {where_sql}
                """
                total = int(storage._conn.execute(count_sql, params).fetchone()[0] or 0)

                data_sql = f"""
                    SELECT
                        f.url,
                        f.title,
                        f.original_filename,
                        f.source_site,
                        f.bytes,
                        f.last_seen,
                        c.category,
                        c.markdown_updated_at
                    FROM files f
                    JOIN catalog_items c ON c.file_url = f.url
                    WHERE {where_sql}
                    ORDER BY f.last_seen DESC, f.id DESC
                    LIMIT ? OFFSET ?
                """
                rows = storage._conn.execute(data_sql, params + [limit, offset]).fetchall()
                files = [
                    {
                        "url": row[0],
                        "title": row[1] or "",
                        "original_filename": row[2] or "",
                        "source_site": row[3] or "",
                        "bytes": row[4] or 0,
                        "last_seen": row[5],
                        "category": row[6] or "",
                        "markdown_updated_at": row[7],
                    }
                    for row in rows
                ]

                return _api_success(
                    {
                        "files": files,
                        "total": total,
                        "limit": limit,
                        "offset": offset,
                        "kb_id": kb_id or None,
                    }
                )

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error listing selectable RAG files")
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>/categories", methods=["GET"])
    @require_permissions("catalog.read")
    def api_rag_get_kb_categories(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)

            def _run(kb_manager, _storage):
                if not kb_manager.get_kb(kid):
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                categories = kb_manager.get_kb_categories(kid)
                return _api_success({"kb_id": kid, "categories": categories, "count": len(categories)})

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error getting KB categories %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>/categories", methods=["POST"])
    @require_permissions("config.write")
    def api_rag_link_kb_categories(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        if (r := _check_config_write_auth()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)
            data = request.get_json(silent=True)
            if not isinstance(data, dict):
                return _api_error("Invalid JSON body", status_code=400)
            categories = _list(data.get("categories"), "categories")
            if not categories:
                return _api_error("categories must be a non-empty list", status_code=400)

            def _run(kb_manager, _storage):
                if not kb_manager.get_kb(kid):
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                before_n = int(kb_manager.get_kb_stats(kid).get("total_files", 0))
                kb_manager.link_kb_to_categories(kid, categories)
                after_n = int(kb_manager.get_kb_stats(kid).get("total_files", 0))
                return _api_success(
                    {
                        "kb_id": kid,
                        "linked_count": len(categories),
                        "files_added": max(0, after_n - before_n),
                    }
                )

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error linking KB categories %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>/stats", methods=["GET"])
    @require_permissions("catalog.read")
    def api_rag_get_kb_stats(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)

            def _run(kb_manager, _storage):
                if not kb_manager.get_kb(kid):
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                return _api_success(kb_manager.get_kb_stats(kid))

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error getting KB stats %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>/files/pending", methods=["GET"])
    @require_permissions("catalog.read")
    def api_rag_get_pending_files(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)

            def _run(kb_manager, _storage):
                if not kb_manager.get_kb(kid):
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                pending = set(kb_manager.get_files_needing_index(kid))
                rows = []
                for item in kb_manager.get_kb_files(kid):
                    if item.get("file_url") not in pending:
                        continue
                    rows.append(
                        {
                            "file_url": item.get("file_url"),
                            "title": item.get("title") or "",
                            "category": item.get("category") or "",
                            "added_at": item.get("added_at"),
                            "indexed_at": item.get("indexed_at"),
                            "markdown_updated_at": item.get("markdown_updated_at"),
                        }
                    )
                return _api_success({"kb_id": kid, "pending_count": len(rows), "pending_files": rows})

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error listing pending KB files %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/task-metadata", methods=["POST"])
    @require_permissions("catalog.read")
    def api_rag_task_metadata():
        if (r := _check_rag_available()) is not None:
            return r
        try:
            data = request.get_json(silent=True)
            if not isinstance(data, dict):
                return _api_error("Invalid JSON body", status_code=400)
            kid = _kb_id(data.get("kb_id"))
            categories = _list(data.get("categories"), "categories")

            def _run(kb_manager, _storage):
                if not kb_manager.get_kb(kid):
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                return _api_success(kb_manager.get_rag_task_metadata(kid, categories or None))

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error getting RAG task metadata")
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>/index", methods=["POST"])
    @require_permissions("tasks.run")
    def api_rag_create_index_task(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        if (r := _check_config_write_auth()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)
            data = request.get_json(silent=True) or {}
            if not isinstance(data, dict):
                return _api_error("Invalid JSON body", status_code=400)
            force_reindex = bool(data.get("force_reindex", False) or data.get("reindex_all", False))
            incremental = bool(data.get("incremental", True))
            requested = _list(data.get("file_urls"), "file_urls")

            def _run(kb_manager, _storage):
                kb = kb_manager.get_kb(kid)
                if not kb:
                    return _api_error(f"Knowledge base '{kid}' not found", status_code=404)
                user_requested = bool(requested)
                files_to_index = requested
                if not files_to_index:
                    if force_reindex or not incremental:
                        files_to_index = [row.get("file_url") for row in kb_manager.get_kb_files(kid)]
                        files_to_index = [url for url in files_to_index if url]
                    else:
                        files_to_index = kb_manager.get_files_needing_index(kid)
                if not files_to_index:
                    return _api_error("No files to index", status_code=400)

                skipped_no_markdown = 0
                if not user_requested:
                    # Auto mode: index only files with markdown content.
                    # Use batching to avoid SQLite parameter limit (999 by default).
                    markdown_urls = set()
                    batch_size = 900  # Stay well under 999 parameter limit
                    for i in range(0, len(files_to_index), batch_size):
                        batch = files_to_index[i:i + batch_size]
                        placeholders = ",".join(["?" for _ in batch])
                        markdown_rows = _storage._conn.execute(
                            f"""
                                SELECT DISTINCT file_url
                                FROM catalog_items
                                WHERE file_url IN ({placeholders})
                                  AND markdown_content IS NOT NULL
                                  AND markdown_content != ''
                            """,
                            batch,
                        ).fetchall()
                        markdown_urls.update(row[0] for row in markdown_rows if row and row[0])
                    original_count = len(files_to_index)
                    files_to_index = [url for url in files_to_index if url in markdown_urls]
                    skipped_no_markdown = max(0, original_count - len(files_to_index))
                    if not files_to_index:
                        return _api_error(
                            "No markdown files to index (all candidates missing markdown)",
                            status_code=400,
                        )

                task_payload = {
                    "type": "rag_indexing",
                    "kb_id": kid,
                    "file_urls": files_to_index,
                    "force_reindex": force_reindex,
                    "incremental": incremental,
                    "name": f"RAG Indexing: {kb.name}",
                }
                if start_background_task is not None:
                    task_id = start_background_task(
                        "rag_indexing",
                        task_payload,
                        task_name=f"RAG Indexing: {kb.name}",
                        extra_fields={"kb_id": kid, "kb_name": kb.name, "rag_file_count": len(files_to_index)},
                    )
                else:
                    task_id = f"rag_index_{kid}_{int(datetime.now().timestamp())}"
                return _api_success(
                    {
                        "job_id": task_id,
                        "kb_id": kid,
                        "file_count": len(files_to_index),
                        "skipped_no_markdown": skipped_no_markdown,
                        "force_reindex": force_reindex,
                        "incremental": incremental,
                        "status": "pending",
                    },
                    status_code=202,
                )

            return _with_manager(_run)
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error creating RAG index task for %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/knowledge-bases/<kb_id>/tasks", methods=["GET"])
    @require_permissions("tasks.view")
    def api_rag_list_kb_tasks(kb_id: str):
        if (r := _check_rag_available()) is not None:
            return r
        try:
            kid = _kb_id(kb_id)
            limit_raw = request.args.get("limit", "20")
            try:
                limit = max(1, min(int(limit_raw), 200))
            except ValueError:
                limit = 20

            if get_kb_tasks is not None:
                payload = get_kb_tasks(kid, limit)
            else:
                history_path = Path("data") / "job_history.jsonl"
                history: list[dict[str, Any]] = []
                if history_path.exists():
                    for line in history_path.read_text(encoding="utf-8", errors="replace").splitlines():
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            task = json.loads(line)
                        except json.JSONDecodeError:
                            continue
                        if task.get("type") == "rag_indexing" and task.get("kb_id") == kid:
                            history.append(task)
                history.sort(key=lambda t: t.get("started_at", ""), reverse=True)
                payload = {"active": [], "history": history[:limit]}

            return _api_success(
                {
                    "kb_id": kid,
                    "active": payload.get("active", []),
                    "history": payload.get("history", []),
                    "active_count": len(payload.get("active", [])),
                    "history_count": len(payload.get("history", [])),
                }
            )
        except ValueError as exc:
            return _api_error(str(exc), status_code=400)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error listing KB tasks %s", kb_id)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    @app.route("/api/rag/files/preview", methods=["GET"])
    @require_permissions("files.read")
    def api_rag_file_preview():
        """
        Get file preview data including original file info, markdown content, and chunks.
        
        Query params:
            file_url: URL of the file to preview
            kb_id: (optional) Knowledge base ID to get chunks from specific KB
        
        Returns:
            - file_info: Basic file metadata
            - markdown_content: Markdown content if available
            - chunks: List of chunks with their content and metadata
        """
        if (r := _check_rag_available()) is not None:
            return r
        
        file_url = request.args.get("file_url", "").strip()
        kb_id = request.args.get("kb_id", "").strip()
        
        if not file_url:
            return _api_error("file_url parameter is required", status_code=400)
        
        try:
            def _run(kb_manager, storage):
                # Get file metadata
                file_info = storage.get_file_by_url(file_url)
                if not file_info:
                    return _api_error("File not found", status_code=404)
                
                # Get markdown content
                markdown_data = storage.get_file_markdown(file_url)
                markdown_content = markdown_data.get("markdown_content", "") if markdown_data else ""
                markdown_source = markdown_data.get("markdown_source", "") if markdown_data else ""
                markdown_updated_at = markdown_data.get("markdown_updated_at", "") if markdown_data else ""
                
                # Get chunks if KB ID provided
                chunks = []
                if kb_id:
                    try:
                        kid = _kb_id(kb_id)
                        # Query chunks from database
                        chunk_rows = storage._conn.execute(
                            """
                            SELECT chunk_id, chunk_index, content, token_count, 
                                   section_hierarchy, created_at
                            FROM rag_chunks
                            WHERE kb_id = ? AND file_url = ?
                            ORDER BY chunk_index
                            """,
                            (kid, file_url)
                        ).fetchall()
                        
                        for row in chunk_rows:
                            chunks.append({
                                "chunk_id": row[0],
                                "chunk_index": row[1],
                                "content": row[2],
                                "token_count": row[3],
                                "section_hierarchy": row[4],
                                "created_at": row[5]
                            })
                    except ValueError:
                        # Invalid KB ID, just skip chunks
                        pass
                
                return _api_success({
                    "file_info": {
                        "url": file_info["url"],
                        "title": file_info["title"],
                        "original_filename": file_info.get("original_filename", ""),
                        "local_path": file_info.get("local_path", ""),
                        "content_type": file_info.get("content_type", ""),
                        "bytes": file_info.get("bytes", 0),
                        "sha256": file_info.get("sha256", ""),
                        "last_modified": file_info.get("last_modified", ""),
                    },
                    "markdown": {
                        "content": markdown_content,
                        "source": markdown_source,
                        "updated_at": markdown_updated_at
                    },
                    "chunks": chunks
                })
            
            return _with_manager(_run)
        except Exception as exc:  # noqa: BLE001
            logger.exception("Error getting file preview for %s", file_url)
            return _api_error("Internal server error", status_code=500, detail=str(exc))

    logger.info("RAG API routes registered successfully")
